/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.2.0.18.0
    Soft IP Version: 1.4.3
    2023 01 22 23:50:51
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module myDphy (axis_mtvalid_o, axis_mtdata_o, axis_stready_i, clk_byte_o,
    clk_byte_hs_o, clk_byte_fr_i, reset_n_i, reset_byte_n_i, reset_byte_fr_n_i,
    clk_p_io, clk_n_io, d_p_io, d_n_io, lp_d_rx_p_o, lp_d_rx_n_o, bd_o,
    hs_sync_o, ref_dt_i, tx_rdy_i, pd_dphy_i, sp_en_o, lp_en_o, lp_av_en_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    output  axis_mtvalid_o;
    output  [47:0]  axis_mtdata_o;
    input  axis_stready_i;
    output  clk_byte_o;
    output  clk_byte_hs_o;
    input  clk_byte_fr_i;
    input  reset_n_i;
    input  reset_byte_n_i;
    input  reset_byte_fr_n_i;
    inout  clk_p_io;
    inout  clk_n_io;
    inout  [1:0]  d_p_io;
    inout  [1:0]  d_n_io;
    output  [1:0]  lp_d_rx_p_o;
    output  [1:0]  lp_d_rx_n_o;
    output  [15:0]  bd_o;
    output  hs_sync_o;
    input  [5:0]  ref_dt_i;
    input  tx_rdy_i;
    input  pd_dphy_i;
    output  sp_en_o;
    output  lp_en_o;
    output  lp_av_en_o;
endmodule